# Generated by Django 4.2.1 on 2023-07-28 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 7, 28, 21, 53, 32, 115729, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='OrderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_partner_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('tracking_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_price', models.PositiveIntegerField()),
                ('additional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_discount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list_id', models.UUIDField()),
                ('total_price', models.PositiveIntegerField()),
                ('additional_charges', models.DecimalField(decimal_places=1, max_digits=10)),
                ('coupon_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
