# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_products', '0002_initial'),
        ('lyka_customer', '0003_initial'),
        ('lyka_address', '0003_initial'),
        ('lyka_order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_products.product'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_products.color'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_products.variations'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_add', to='lyka_address.customeraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_order.ordercredentials'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_order.orderitems'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_order.orderlist'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_address.sellerstoreaddress'),
        ),
    ]
