# Generated by Django 4.2.1 on 2023-07-29 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 13, 19, 174830, tzinfo=datetime.timezone.utc)),
        ),
    ]
