# Generated by Django 4.2.1 on 2023-07-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0005_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 17, 43, 15, 57416, tzinfo=datetime.timezone.utc)),
        ),
    ]
