# Generated by Django 4.2.1 on 2023-08-01 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0011_ordergroup_alter_order_time_order_order_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_group',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 29, 27, 950619, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='OrderGroup',
        ),
    ]
