# Generated by Django 4.2.1 on 2023-08-01 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_address', '0003_initial'),
        ('lyka_order', '0013_ordergroup_alter_order_time_order_order_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_add', to='lyka_address.customeraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_add', to='lyka_address.customeraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 21, 43, 37, 32306, tzinfo=datetime.timezone.utc)),
        ),
    ]
