# Generated by Django 4.2.1 on 2023-08-01 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0014_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 22, 1, 35, 756630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
