# Generated by Django 4.2.1 on 2023-08-03 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_address', '0003_initial'),
        ('lyka_payment', '0004_remove_coupontype_discount_amount'),
        ('lyka_order', '0017_order_payment_method_ordergroup_total_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_payment.coupontype'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='applied_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_payment.coupontype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_address.sellerstoreaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 18, 50, 25, 781395, tzinfo=datetime.timezone.utc)),
        ),
    ]
