# Generated by Django 4.2.1 on 2023-08-03 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0018_order_applied_coupon_ordergroup_applied_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 22, 42, 42, 499200, tzinfo=datetime.timezone.utc)),
        ),
    ]
