# Generated by Django 4.2.1 on 2023-08-04 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0019_orderitems_original_price_alter_order_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 13, 8, 19, 147848, tzinfo=datetime.timezone.utc)),
        ),
    ]
