# Generated by Django 4.2.1 on 2023-08-05 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0021_order_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 16, 22, 39, 759793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ordercredentials',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordercredentials',
            name='shipping_partner_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordercredentials',
            name='tracking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
