# Generated by Django 4.2.1 on 2023-08-06 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0025_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 16, 48, 56, 808719, tzinfo=datetime.timezone.utc)),
        ),
    ]
