# Generated by Django 4.2.1 on 2023-08-06 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0026_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 18, 34, 28, 837761, tzinfo=datetime.timezone.utc)),
        ),
    ]
