# Generated by Django 4.2.1 on 2023-08-07 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0027_order_delivery_date_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 16, 54, 52, 303416, tzinfo=datetime.timezone.utc)),
        ),
    ]
