# Generated by Django 4.2.1 on 2023-08-07 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0030_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 20, 54, 52, 570409, tzinfo=datetime.timezone.utc)),
        ),
    ]
