# Generated by Django 4.2.1 on 2023-08-08 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0031_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 16, 59, 44, 226415, tzinfo=datetime.timezone.utc)),
        ),
    ]
