# Generated by Django 4.2.1 on 2023-08-12 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0034_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 17, 36, 25, 768032, tzinfo=datetime.timezone.utc)),
        ),
    ]
