# Generated by Django 4.2.1 on 2023-08-14 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0035_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 9, 13, 22, 65505, tzinfo=datetime.timezone.utc)),
        ),
    ]
