# Generated by Django 4.2.1 on 2023-12-26 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0037_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 14, 2, 9, 467950, tzinfo=datetime.timezone.utc)),
        ),
    ]
