# Generated by Django 4.2.1 on 2024-01-07 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0041_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 12, 28, 20, 829038, tzinfo=datetime.timezone.utc)),
        ),
    ]
