# Generated by Django 4.2.1 on 2024-01-08 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0042_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 10, 44, 22, 149684, tzinfo=datetime.timezone.utc)),
        ),
    ]
