# Generated by Django 5.0 on 2024-01-09 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0043_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 14, 15, 53, 689945, tzinfo=datetime.timezone.utc)),
        ),
    ]
