# Generated by Django 4.2.9 on 2024-01-10 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0046_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'PLACED'), ('CONFIRMED', 'CONFIRMED'), ('PICKED UP', 'PICKED UP'), ('SHIPPED', 'SHIPPED'), ('IN TRANSIST', 'IN TRANSIST'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('DELIVERED', 'DELIVERED')], default='PLACED'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 18, 42, 8, 177485, tzinfo=datetime.timezone.utc)),
        ),
    ]
