# Generated by Django 4.2.9 on 2024-01-20 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0047_order_status_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PLACED', 'PLACED'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED'), ('PICKED UP', 'PICKED UP'), ('SHIPPED', 'SHIPPED'), ('IN TRANSIST', 'IN TRANSIST'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('DELIVERED', 'DELIVERED')], default='CREATED'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 17, 8, 34, 640529, tzinfo=datetime.timezone.utc)),
        ),
    ]
