# Generated by Django 4.2.9 on 2024-01-22 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0048_alter_order_status_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 20, 42, 58, 132481, tzinfo=datetime.timezone.utc)),
        ),
    ]
