# Generated by Django 4.2.9 on 2024-01-24 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0049_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 9, 59, 21, 846467, tzinfo=datetime.timezone.utc)),
        ),
    ]
