# Generated by Django 4.2.9 on 2024-02-10 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_order', '0050_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 9, 25, 51, 605937, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
