# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_cart', '0003_initial'),
        ('lyka_products', '0002_initial'),
        ('lyka_customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_products.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_cart.cart'),
        ),
    ]
