# Generated by Django 4.2.1 on 2023-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_customer', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
