# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lyka_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LykaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('is_customer', models.BooleanField(null=True)),
                ('is_seller', models.BooleanField(null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('ADMIN', 'Admin')], max_length=10)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
