# Generated by Django 4.2.1 on 2023-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_user', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
