# Generated by Django 4.2.1 on 2024-01-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_user', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreationAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('ADMIN', 'Admin')], max_length=50)),
            ],
        ),
    ]
