# Generated by Django 4.2.1 on 2024-01-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_user', '0004_usercreationauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreationauth',
            name='token',
            field=models.CharField(max_length=250),
        ),
    ]
