# Generated by Django 4.2.1 on 2024-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_user', '0005_alter_usercreationauth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lykauser',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lykauser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
