# Generated by Django 4.2.1 on 2023-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_address', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerstoreaddress',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
