# Generated by Django 4.2.9 on 2024-01-22 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=False)),
                ('ref_no', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Total_Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_no', models.IntegerField()),
            ],
        ),
    ]
