# Generated by Django 4.2.9 on 2024-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_commission',
            name='total_no',
            field=models.IntegerField(default=0),
        ),
    ]
