# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('main_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('main_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('root_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('root_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('sub_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sub_slug', models.SlugField(unique=True)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_categories.main')),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_categories.root'),
        ),
    ]
