# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_seller', '0002_initial'),
        ('lyka_payment', '0002_initial'),
        ('lyka_order', '0004_initial'),
        ('lyka_customer', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_seller.seller'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_order.order'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_seller.seller'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_customer.customer'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_payment.wallet'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_payment.coupontype'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_customer.customer'),
        ),
    ]
