# Generated by Django 4.2.1 on 2023-08-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_payment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupontype',
            name='discount_amount',
        ),
    ]
