# Generated by Django 4.2.1 on 2023-08-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_payment', '0009_alter_ordertransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
