# Generated by Django 4.2.1 on 2023-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_payment', '0010_alter_salesreport_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_products_sold',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
