# Generated by Django 4.2.1 on 2023-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_payment', '0011_alter_salesreport_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='total_amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='total_refunds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
