# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_proof_number', models.CharField(blank=True, max_length=200, null=True)),
                ('address_proof_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_proff_dob', models.CharField(blank=True, max_length=200, null=True)),
                ('address_proof_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GstRegistrationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PickupStore',
            fields=[
                ('store_name', models.CharField(max_length=50)),
                ('store_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellerOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=9, null=True)),
                ('verification_credential', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('unique_id', models.UUIDField(primary_key=True, serialize=False)),
                ('bussiness_name', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('number_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('pan_verified', models.BooleanField(default=False)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('gstin_verified', models.BooleanField(default=False)),
                ('address_proof', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_seller.addressproof')),
                ('bank_account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_seller.bankaccount')),
                ('gstin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_seller.gstregistrationnumber')),
                ('pan_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_seller.pancard')),
            ],
        ),
    ]
