# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyka_payment', '0003_initial'),
        ('lyka_seller', '0002_initial'),
        ('lyka_address', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller',
            name='wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_payment.wallet'),
        ),
        migrations.AddField(
            model_name='pickupstore',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to='lyka_seller.seller'),
        ),
        migrations.AddField(
            model_name='pickupstore',
            name='store_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_address.sellerstoreaddress'),
        ),
    ]
