# Generated by Django 4.2.1 on 2023-08-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_seller', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='wallet',
        ),
    ]
