# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_products', '0002_initial'),
        ('lyka_seller', '0002_initial'),
        ('lyka_categories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_seller.seller'),
        ),
        migrations.AddField(
            model_name='unit',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_products.variations'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='lyka_products.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_products.details'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='lyka_products.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lyka_categories.main'),
        ),
        migrations.AddField(
            model_name='product',
            name='root_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lyka_categories.root'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lyka_categories.sub'),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(to='lyka_products.variations'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='lyka_products.product'),
        ),
        migrations.AddField(
            model_name='details',
            name='product_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lyka_categories.main'),
        ),
    ]
