# Generated by Django 4.2.1 on 2023-07-29 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 13, 19, 158522, tzinfo=datetime.timezone.utc)),
        ),
    ]
