# Generated by Django 4.2.1 on 2023-07-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0004_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 17, 43, 15, 37318, tzinfo=datetime.timezone.utc)),
        ),
    ]
