# Generated by Django 4.2.1 on 2023-08-01 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0017_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 22, 1, 35, 744617, tzinfo=datetime.timezone.utc)),
        ),
    ]
