# Generated by Django 4.2.1 on 2023-08-10 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0036_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 7, 16, 9, 207024, tzinfo=datetime.timezone.utc)),
        ),
    ]
