# Generated by Django 4.2.1 on 2023-12-26 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0040_product_verified_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 14, 2, 9, 462625, tzinfo=datetime.timezone.utc)),
        ),
    ]
