# Generated by Django 5.0 on 2024-01-09 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0046_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 14, 15, 53, 681426, tzinfo=datetime.timezone.utc)),
        ),
    ]
