# Generated by Django 4.2.9 on 2024-01-09 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0048_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 20, 25, 53, 953013, tzinfo=datetime.timezone.utc)),
        ),
    ]
