# Generated by Django 4.2.9 on 2024-01-22 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0051_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 20, 42, 58, 125851, tzinfo=datetime.timezone.utc)),
        ),
    ]
