# Generated by Django 4.2.9 on 2024-01-24 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0052_alter_unit_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 9, 59, 21, 821778, tzinfo=datetime.timezone.utc)),
        ),
    ]
