# Generated by Django 4.2.9 on 2024-02-10 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_products', '0053_alter_product_options_product_added_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-added_on']},
        ),
        migrations.AlterField(
            model_name='unit',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 9, 25, 51, 598941, tzinfo=datetime.timezone.utc)),
        ),
    ]
