# Generated by Django 4.2.1 on 2023-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyka_products', '0002_initial'),
        ('lyka_cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyka_products.product'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyka_products.unit'),
        ),
    ]
