# Generated by Django 4.2.1 on 2023-07-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_cart', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='item',
        ),
    ]
