# Generated by Django 4.2.1 on 2023-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyka_cart', '0004_remove_cartitems_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
